# Minecraft Realistic Roleplay
# configuration file

# General server settings
settings:

  # Website shown to unregistered players.
  website: "http://example.com"

  # Default language
  lang: en

  # Set to true to enable offline mode.
  # If enabled, anyone can login to the server using any nickname and no password.
  # Warning: this feature should be for testing purpose only!
  offline: false

# Database management system identifiers.
# Using MariaDB Server is recommended.
database:
  host: localhost
  name: mcrrp
  user: root
  pass:

# Initial city data
city:
   name: Toblerone
   governor: Olybri
